version: '3.8'

services:
  article-db:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  db_data: {}
